### ISSUE TITLE
请问项目完整吗？

### ISSUE THREAD

**Issue by yqchilde** [biningo/note-gin#3]
您好，拉取下来跑不出来，1是缺少yaml文件，2是没看到在哪里去newConfig

**Comment by biningo** [comment]
yaml文件是外部配置的，启动服务器时输入总配置的yaml文件的绝对路径，总的yaml里面记录了各个配置的yaml文件的路径，然后根据yaml文件路径去寻找各个模块的配置。直接把yaml文件存config目录下即可。启动输入的总yaml文件只是集成作用，记录各个模块的yaml文件路径。**后续我会出一个完整的教程**。有错误再提issue吧
