### ISSUE TITLE
请问可以提供本地部署的方法么

### ISSUE THREAD

**Issue by univana** [biningo/note-gin#4]
挺喜欢这个项目的，希望能够在本地部署学习

**Comment by biningo** [comment]
ok 过几天准备改进一下 感觉配置整的太麻烦了   到时候一起上传部署方法 感谢持续关注 多谢

**Comment by biningo** [comment]
已上传本地部署方法，有疑问欢迎再提issue

**Comment by YUbuntu0109** [comment]
> 欢迎

so where I can view that ?

**Comment by GoogTech** [comment]
> 已上传本地部署方法，有疑问欢迎再提issue

so where I can view that bro ?
