### ISSUE TITLE
axiox怎么换成自己的呢

### ISSUE THREAD

**Issue by xianpc** [biningo/note-gin#6]
axiox怎么配置，能出份教程吗

**Comment by xianpc** [comment]
我感觉配置了vue.config.js 的地址，没起作用，改了request.js中的url显示一直加载中，后端访问localhost:9000//ping是成功的,

**Comment by biningo** [comment]
在前端的network文件夹里的requests.js里的bashUrl和vue.config.js 里一致吗

**Comment by biningo** [comment]
url一直加载就是跨域出了问题，其他没问题

**Comment by xianpc** [comment]
你好：
&nbsp;&nbsp;&nbsp;&nbsp; 我把baseURL设置成跟你的一样，target 随便设置都能成功访问页面，内容是你的。我把baseURL设置成自己的，访问页面，gin后端日志成功刷出，应该是请求成功了，但是前端一直显示数据加载中，可能是那儿的问题呢？



这儿我怀疑是/api路径映射不对，改为：baseURL: 'http://127.0.0.1:9000/api' -&gt;&nbsp; baseURL: 'http://127.0.0.1:9000'


改完之后应该是正常请求，但是页面是一直加载中，我感觉下面这个好像没生效
proxy: {
    '/api': {    // search为转发路径
        target: 'http://127.0.0.1:9000',  // 后端地址
        ws: true, // 是否代理websockets
        changeOrigin: true,  // 设置同源  默认false，是否需要改变原始主机头为目标URL,
        pathRewrite: {
            '^/api/': ''   // 把 '/api/user' 替换为 '/user'
        }
    }
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"biningo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月7日(星期天) 晚上6:32
收件人:&nbsp;"biningo/note-gin"<note-gin@noreply.github.com&gt;;
抄送:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [biningo/note-gin] axiox怎么换成自己的呢 (#6)





 
在前端的network文件夹里的requests.js里的bashUrl和vue.config.js 里一致吗

**Comment by xianpc** [comment]
会不会是资源文件夹不存在造成的？
资源文件又是怎么一个目录结构呢？

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 上午10:07
收件人:&nbsp;"biningo/note-gin"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [biningo/note-gin] axiox怎么换成自己的呢 (#6)




你好：
&nbsp;&nbsp; &nbsp; 我把baseURL设置成跟你的一样，target 随便设置都能成功访问页面，内容是你的。我把baseURL设置成自己的，访问页面，gin后端日志成功刷出，应该是请求成功了，但是前端一直显示数据加载中，可能是那儿的问题呢？



这儿我怀疑是/api路径映射不对，改为：baseURL: 'http://127.0.0.1:9000/api' -&gt;&nbsp; baseURL: 'http://127.0.0.1:9000'


改完之后应该是正常请求，但是页面是一直加载中，我感觉下面这个好像没生效
proxy: {
    '/api': {    // search为转发路径
        target: 'http://127.0.0.1:9000',  // 后端地址
        ws: true, // 是否代理websockets
        changeOrigin: true,  // 设置同源  默认false，是否需要改变原始主机头为目标URL,
        pathRewrite: {
            '^/api/': ''   // 把 '/api/user' 替换为 '/user'
        }
    }
}





------------------ 原始邮件 ------------------
发件人:&nbsp;"biningo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月7日(星期天) 晚上6:32
收件人:&nbsp;"biningo/note-gin"<note-gin@noreply.github.com&gt;;
抄送:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [biningo/note-gin] axiox怎么换成自己的呢 (#6)





 
在前端的network文件夹里的requests.js里的bashUrl和vue.config.js 里一致吗

**Comment by xianpc** [comment]
不好意思，上封邮件不对，后端忘运行了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 上午10:41
收件人:&nbsp;"biningo/note-gin"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [biningo/note-gin] axiox怎么换成自己的呢 (#6)







会不会是资源文件夹不存在造成的？
资源文件又是怎么一个目录结构呢？

------------------ 原始邮件 ------------------
发件人:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 上午10:07
收件人:&nbsp;"biningo/note-gin"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [biningo/note-gin] axiox怎么换成自己的呢 (#6)




你好：
&nbsp;&nbsp; &nbsp; 我把baseURL设置成跟你的一样，target 随便设置都能成功访问页面，内容是你的。我把baseURL设置成自己的，访问页面，gin后端日志成功刷出，应该是请求成功了，但是前端一直显示数据加载中，可能是那儿的问题呢？



这儿我怀疑是/api路径映射不对，改为：baseURL: 'http://127.0.0.1:9000/api' -&gt;&nbsp; baseURL: 'http://127.0.0.1:9000'


改完之后应该是正常请求，但是页面是一直加载中，我感觉下面这个好像没生效
proxy: {
    '/api': {    // search为转发路径
        target: 'http://127.0.0.1:9000',  // 后端地址
        ws: true, // 是否代理websockets
        changeOrigin: true,  // 设置同源  默认false，是否需要改变原始主机头为目标URL,
        pathRewrite: {
            '^/api/': ''   // 把 '/api/user' 替换为 '/user'
        }
    }
}





------------------ 原始邮件 ------------------
发件人:&nbsp;"biningo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月7日(星期天) 晚上6:32
收件人:&nbsp;"biningo/note-gin"<note-gin@noreply.github.com&gt;;
抄送:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [biningo/note-gin] axiox怎么换成自己的呢 (#6)





 
在前端的network文件夹里的requests.js里的bashUrl和vue.config.js 里一致吗

**Comment by biningo** [comment]
开发环境里 vue运行是用node.js 运行的
比如vue配置端口 9001  go后端配置端口 9000 
axios所有请求 都发送到9001，比如 9001/api/get 请求  
然后设置代理  就变成了   9001/api/get --------------> 9000/get

**Comment by biningo** [comment]
部署到服务器的话我是用nginx作代理，前端只是一些静态资源   axios请求会被nginx代理到go后端

**Comment by xianpc** [comment]
谢谢指导，前后端我调通了，发现了一个bug, PageSize这个变量赋值应当再函数体内，这儿将会是一个空指针。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"biningo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 中午11:27
收件人:&nbsp;"biningo/note-gin"<note-gin@noreply.github.com&gt;;
抄送:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [biningo/note-gin] axiox怎么换成自己的呢 (#6)





 
部署到服务器的话我是用nginx作代理，前端只是一些静态资源   axios请求会被nginx代理到go后端

**Comment by biningo** [comment]
ok 多谢提醒  具体是哪个文件哪行代码呢？ 我看看

**Comment by biningo** [comment]
提交pr也可

**Comment by xianpc** [comment]
我之前连接楼主的服务器没有这些问题的，本地调试才出现的
1. note-gin-master/models/Folder.go&nbsp;&nbsp;&nbsp; 第八行，PageSize 的定义
2. note-gin-master\controller\ArticleController\Create.go&nbsp;&nbsp; 第15行，err 没有判断nil, 直接使用了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"biningo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午4:28
收件人:&nbsp;"biningo/note-gin"<note-gin@noreply.github.com&gt;;
抄送:&nbsp;"感觉走•°°•"<1024163476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [biningo/note-gin] axiox怎么换成自己的呢 (#6)





 
提交pr也可

**Comment by biningo** [comment]
ok 多谢提醒 共同学习
