### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by zhenghaohong** [biningo/note-gin#7]
mysql数据库都配好了 但是还是报连接mysql的错误
![image](https://user-images.githubusercontent.com/29895172/85940824-7682e200-b951-11ea-84ea-1f304812ced6.png)

**Comment by biningo** [comment]
mysql数据库的用户名和密码配对了吗？提示好像是连接权限问题

**Comment by biningo** [comment]
还有，第一次运行的时候记得把 migration打开，这样就会自动生成表了，并且在运行前先创建数据库，然后配置上数据库名字DataBaseName

**Comment by zhenghaohong** [comment]
> 还有，第一次运行的时候记得把 migration打开，这样就会自动生成表了，并且在运行前先创建数据库，然后配置上数据库名字DataBaseName

是的呢  数据库创建好了的  权限的话其他项目也是类似这样连接的  还是不行哈

**Comment by biningo** [comment]
你自己的项目用gorm也不能连接数据库吗，把数据库连接的代码用手硬编码输进去看看能不能连接成功

**Comment by biningo** [comment]
![image](https://user-images.githubusercontent.com/54737035/85981147-49e4ce00-ba16-11ea-8635-5180491a8e77.png)
这行代码用手输入硬编码看看能不能成功

**Comment by zhenghaohong** [comment]
> ![image](https://user-images.githubusercontent.com/54737035/85981147-49e4ce00-ba16-11ea-8635-5180491a8e77.png)
> 这行代码用手输入硬编码看看能不能成功

好咧  我试试  谢谢你  好喜欢你的这个项目呀

**Comment by zhenghaohong** [comment]
> 你自己的项目用gorm也不能连接数据库吗，把数据库连接的代码用手硬编码输进去看看能不能连接成功

我自己的项目用gorm连接是可以的  不会报权限的错误哈
